spring:
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/bills-manager-db}
        username: ${DATABASE_USERNAME_APP:bills-manager-app}
        password: ${DATABASE_PASSWORD_APP}
csv:
    contas:
        path: /app/csv/contas/